controller_names:
  - rebel_6dof_controller

rebel_6dof_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - <prefix>joint1
    - <prefix>joint2
    - <prefix>joint3
    - <prefix>joint4
    - <prefix>joint5
    - <prefix>joint6