# Limits for the Pilz planner
# TODO: Currently not used, remove in case pilz won't be supported
cartesian_limits:
  max_trans_vel: 1.0
  max_trans_acc: 2.25
  max_trans_dec: -5.0
  max_rot_vel: 1.57
