# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rebel_6dof_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dio_controller:
      type: irc_ros_controllers/DIOController

    external_dio_controller:
      type: irc_ros_controllers/DIOController

    ecbpmi_controller:
      type: irc_ros_controllers/EcbpmiController

rebel_6dof_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

dio_controller:
  ros__parameters:
    digital_inputs: 
      - dio_arm/digital_input_0
      - dio_arm/digital_input_1
      - dio_base/digital_input_0
      - dio_base/digital_input_1
      - dio_base/digital_input_2
      - dio_base/digital_input_3
      - dio_base/digital_input_4
      - dio_base/digital_input_5
      - dio_base/digital_input_6

    digital_outputs:
      - dio_arm/digital_output_0
      - dio_arm/digital_output_1
      - dio_base/digital_output_0
      - dio_base/digital_output_1
      - dio_base/digital_output_2
      - dio_base/digital_output_3
      - dio_base/digital_output_4
      - dio_base/digital_output_5
      - dio_base/digital_output_6

external_dio_controller:
  ros__parameters:
    digital_inputs: 
      - dio_ext/digital_input_0
      - dio_ext/digital_input_1
      - dio_ext/digital_input_2
      - dio_ext/digital_input_3
      - dio_ext/digital_input_4
      - dio_ext/digital_input_5
      - dio_ext/digital_input_6
    digital_outputs:
      - dio_ext/digital_output_0
      - dio_ext/digital_output_1
      - dio_ext/digital_output_2
      - dio_ext/digital_output_3
      - dio_ext/digital_output_4
      - dio_ext/digital_output_5
      - dio_ext/digital_output_6

ecbpmi_controller:
  ros__parameters:
    output_grip: dio_arm/digital_output_0
    output_release: dio_arm/digital_output_1
    input_grasped: dio_arm/digital_input_0
 