# This config file is used by ros2_control
<namespace>/controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rebel_6dof_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dio_controller:
      type: irc_ros_controllers/DIOController

    external_dio_controller:
      type: irc_ros_controllers/DIOController

    ecbpmi_controller:
      type: irc_ros_controllers/EcbpmiController

<namespace>/rebel_6dof_controller:
  ros__parameters:
    joints:
      - <prefix>joint1
      - <prefix>joint2
      - <prefix>joint3
      - <prefix>joint4
      - <prefix>joint5
      - <prefix>joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

<namespace>/dio_controller:
  ros__parameters:
    digital_inputs: 
      - <prefix>dio_arm/digital_input_0
      - <prefix>dio_arm/digital_input_1
      - <prefix>dio_base/digital_input_0
      - <prefix>dio_base/digital_input_1
      - <prefix>dio_base/digital_input_2
      - <prefix>dio_base/digital_input_3
      - <prefix>dio_base/digital_input_4
      - <prefix>dio_base/digital_input_5
      - <prefix>dio_base/digital_input_6

    digital_outputs:
      - <prefix>dio_arm/digital_output_0
      - <prefix>dio_arm/digital_output_1
      - <prefix>dio_base/digital_output_0
      - <prefix>dio_base/digital_output_1
      - <prefix>dio_base/digital_output_2
      - <prefix>dio_base/digital_output_3
      - <prefix>dio_base/digital_output_4
      - <prefix>dio_base/digital_output_5
      - <prefix>dio_base/digital_output_6

<namespace>/external_dio_controller:
  ros__parameters:
    digital_inputs: 
      - <prefix>dio_ext/digital_input_0
      - <prefix>dio_ext/digital_input_1
      - <prefix>dio_ext/digital_input_2
      - <prefix>dio_ext/digital_input_3
      - <prefix>dio_ext/digital_input_4
      - <prefix>dio_ext/digital_input_5
      - <prefix>dio_ext/digital_input_6
    digital_outputs:
      - <prefix>dio_ext/digital_output_0
      - <prefix>dio_ext/digital_output_1
      - <prefix>dio_ext/digital_output_2
      - <prefix>dio_ext/digital_output_3
      - <prefix>dio_ext/digital_output_4
      - <prefix>dio_ext/digital_output_5
      - <prefix>dio_ext/digital_output_6

<namespace>/ecbpmi_controller:
  ros__parameters:
    output_grip: <prefix>dio_arm/digital_output_0
    output_release: <prefix>dio_arm/digital_output_1
    input_grasped: <prefix>dio_arm/digital_input_0
 