<namespace>/controller_manager:
  ros__parameters:
    update_rate: 100 # 100Hz for CAN and 10Hz for CRI

    external_dio_controller:
      type: irc_ros_controllers/DIOController


<namespace>/external_dio_controller:
  ros__parameters:
    digital_inputs: 
      - <prefix>dio_ext/digital_input_0
      - <prefix>dio_ext/digital_input_1
      - <prefix>dio_ext/digital_input_2
      - <prefix>dio_ext/digital_input_3
      - <prefix>dio_ext/digital_input_4
      - <prefix>dio_ext/digital_input_5
      - <prefix>dio_ext/digital_input_6
    digital_outputs:
      - <prefix>dio_ext/digital_output_0
      - <prefix>dio_ext/digital_output_1
      - <prefix>dio_ext/digital_output_2
      - <prefix>dio_ext/digital_output_3
      - <prefix>dio_ext/digital_output_4
      - <prefix>dio_ext/digital_output_5
      - <prefix>dio_ext/digital_output_6