<namespace>/controller_manager:
  ros__parameters:
    update_rate: 100 # 100Hz for CAN and 10Hz for CRI

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    dio_controller:
      type: irc_ros_controllers/DIOController

<namespace>/joint_trajectory_controller:
  ros__parameters:
    joints: 
      - <prefix>joint1
      - <prefix>joint2
      - <prefix>joint3
      - <prefix>joint4

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 100.0 # Defaults to 20

    open_loop_control: true
    allow_partial_joints_goal: true

<namespace>/dio_controller:
  ros__parameters:
    digital_inputs: 
      - <prefix>dio_arm/digital_input_0
      - <prefix>dio_arm/digital_input_1
      - <prefix>dio_base/digital_input_0
      - <prefix>dio_base/digital_input_1
      - <prefix>dio_base/digital_input_2
      - <prefix>dio_base/digital_input_3
      - <prefix>dio_base/digital_input_4
      - <prefix>dio_base/digital_input_5
      - <prefix>dio_base/digital_input_6

    digital_outputs:
      - <prefix>dio_arm/digital_output_0
      - <prefix>dio_arm/digital_output_1
      - <prefix>dio_base/digital_output_0
      - <prefix>dio_base/digital_output_1
      - <prefix>dio_base/digital_output_2
      - <prefix>dio_base/digital_output_3
      - <prefix>dio_base/digital_output_4
      - <prefix>dio_base/digital_output_5
      - <prefix>dio_base/digital_output_6