<namespace>/controller_manager:
  ros__parameters:
    update_rate: 100 # 100Hz for CAN and 10Hz for CRI

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

<namespace>/joint_trajectory_controller:
  ros__parameters:
    joints: 
      - <prefix>joint1
      - <prefix>joint2
      - <prefix>joint3
      - <prefix>joint4
      - <prefix>joint5

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 100.0 # Defaults to 20

    open_loop_control: true
    allow_partial_joints_goal: true