/rebel_1/controller_manager:
  ros__parameters:
    update_rate: 100 # 100Hz for CAN and 10Hz for CRI

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

/rebel_1/joint_trajectory_controller:
  ros__parameters:
    controller_name: "rebel_1/joint_trajectory_controller"

    joints: 
      - rebel_1_joint1
      - rebel_1_joint2
      - rebel_1_joint3
      - rebel_1_joint4
      - rebel_1_joint5
      - rebel_1_joint6

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 100.0 # Defaults to 20

    open_loop_control: true
    allow_partial_joints_goal: true