controller_manager:
  ros__parameters:
    update_rate: 100 # 100Hz for CAN and 10Hz for CRI

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# TODO: Add launchfile using this and test it.
# If it works good enough the velocity input and output are good enough and diff drive should also work
    joint_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_effort_controller:
      type: effort_controllers/JointGroupEffortController

    dio_controller:
      type: irc_ros_controllers/DIOController

# TODO: Move to separate control file
    ecbpmi_controller:
      type: irc_ros_controllers/EcbpmiController

    dashboard_controller:
      type: irc_ros_controllers/DashboardController

joint_trajectory_controller:
  ros__parameters:
    joints: 
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 100.0 # Defaults to 20

    open_loop_control: true
    allow_partial_joints_goal: true

joint_velocity_controller:
  ros__parameters:
    joints: 
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      # - velocity

    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 100.0 # Defaults to 20

    open_loop_control: true

joint_effort_controller:
  ros__parameters:
    joints: 
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - effort

    state_interfaces:
      - position

dio_controller:
  ros__parameters:
    digital_inputs: 
      - dio_arm/digital_input_0
      - dio_arm/digital_input_1
      - dio_base/digital_input_0
      - dio_base/digital_input_1
      - dio_base/digital_input_2
      - dio_base/digital_input_3
      - dio_base/digital_input_4
      - dio_base/digital_input_5
      - dio_base/digital_input_6

    digital_outputs:
      - dio_arm/digital_output_0
      - dio_arm/digital_output_1
      - dio_base/digital_output_0
      - dio_base/digital_output_1
      - dio_base/digital_output_2
      - dio_base/digital_output_3
      - dio_base/digital_output_4
      - dio_base/digital_output_5
      - dio_base/digital_output_6

# TODO: Rate limit this from 100Hz
dashboard_controller:
  ros__parameters:
    joints: 
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint_wheel_1
      - joint_wheel_2

    gpios:
      - dio_arm
      - dio_base
      # - dio_ext

    joint_state_interfaces:
      - position
      - velocity
      - effort
    
    joint_command_interface:
      - position
      - velocity
      - effort

    digital_inputs: 
      - dio_arm/digital_input_0
      - dio_arm/digital_input_1
      - dio_base/digital_input_0
      - dio_base/digital_input_1
      - dio_base/digital_input_2
      - dio_base/digital_input_3
      - dio_base/digital_input_4
      - dio_base/digital_input_5
      - dio_base/digital_input_6

    digital_outputs:
      - dio_arm/digital_output_0
      - dio_arm/digital_output_1
      - dio_base/digital_output_0
      - dio_base/digital_output_1
      - dio_base/digital_output_2
      - dio_base/digital_output_3
      - dio_base/digital_output_4
      - dio_base/digital_output_5
      - dio_base/digital_output_6

ecbpmi_controller:
  ros__parameters:
    output_grip: dio_arm/digital_output_0
    output_release: dio_arm/digital_output_1
    input_grasped: dio_arm/digital_input_0
 